using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Client._Stalker.PersistentCrafting;
using Content.Client._Stalker.PersistentCrafting.UI.Coordinators;
using Content.Client._Stalker.PersistentCrafting.UI.Indexes;
using Content.Client._Stalker.PersistentCrafting.UI.ViewModels;
using Content.Shared._Stalker.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftingWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    [Dependency] private readonly IClyde _clyde = default!;

    private static readonly Color PanelBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardUnlockedBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardLockedBackground = PersistentCraftUiTheme.SurfacePanelSoft;
    private static readonly Color CardAvailableBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color UnlockedBorder = PersistentCraftUiTheme.Success;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color HeaderTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color MutedTextColor = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private const float TierTreeNodeWidth = 176f;
    private const float TierTreeNodeHeight = 178f;
    private const float TierTreeHorizontalGap = 56f;
    private const float TierTreeVerticalGap = 36f;
    private const float TierTreePadding = 24f;
    private const float TierTreeLineThickness = 3f;
    private const float NodeDetailsWindowWidth = 860f;
    private const float NodeDetailsWindowHeight = 720f;
    private const float NodeDetailsWindowMinWidth = 700f;
    private const float NodeDetailsWindowMinHeight = 560f;
    private const float NodeDetailsWindowMargin = 16f;

    private readonly Dictionary<string, BoxContainer> _branchHosts = new();
    private readonly PersistentCraftSkillTreeViewModel _viewModel = new();
    private readonly PersistentCraftBranchCoordinator _branchCoordinator;
    private readonly PersistentCraftNodeSelectionCoordinator _selectionCoordinator;
    private readonly PersistentCraftNodeDetailsWindowCoordinator _detailsCoordinator;

    private PersistentCraftRecipeIndex? _recipeIndex;
    private PersistentCraftState? _state;
    private PersistentCraftBranchRegistry _branchRegistry;
    private PersistentCraftClientPrototypeCache? _prototypeCache;
    private IReadOnlyList<PersistentCraftNodePrototype> _nodes = Array.Empty<PersistentCraftNodePrototype>();
    private IReadOnlyList<PersistentCraftRecipePrototype> _recipes = Array.Empty<PersistentCraftRecipePrototype>();
    private Action<string>? _onUnlock;

    public PersistentCraftingWindow()
    {
        IoCManager.InjectDependencies(this);
        _selectionCoordinator = new PersistentCraftNodeSelectionCoordinator(_viewModel);
        _detailsCoordinator = new PersistentCraftNodeDetailsWindowCoordinator(
            _clyde,
            NodeDetailsWindowWidth,
            NodeDetailsWindowHeight,
            NodeDetailsWindowMinWidth,
            NodeDetailsWindowMinHeight,
            NodeDetailsWindowMargin);
        _branchRegistry = PersistentCraftBranchRegistry.Create(_prototype);
        _branchCoordinator = new PersistentCraftBranchCoordinator(_branchRegistry, _branchHosts);

        RobustXamlLoader.Load(this);

        InitializeBranchHosts();
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-skill-tabs", PersistentCraftUiTheme.Selection, _uiManager);

        Branches.OnTabChanged += _ =>
        {
            CloseNodeDetailsWindow();
            RenderBranch(_branchCoordinator.GetCurrentBranch(Branches));
        };
    }

    private void InitializeBranchHosts()
    {
        Branches.RemoveAllChildren();
        _branchHosts.Clear();

        for (var index = 0; index < _branchRegistry.OrderedBranches.Count; index++)
        {
            var definition = _branchRegistry.OrderedBranches[index];
            var host = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(12, 12, 12, 12),
            };

            var scroll = new ScrollContainer
            {
                MinSize = new Vector2(980, 0),
                HorizontalExpand = true,
                HScrollEnabled = true,
                VerticalExpand = true,
            };
            scroll.AddChild(host);
            Branches.AddChild(scroll);

            _branchHosts[definition.ID] = host;
            Branches.SetTabTitle(index, ResolveBranchTitle(definition));
        }
    }

    public override void Close()
    {
        CloseNodeDetailsWindow();
        base.Close();
    }

    public void UpdateState(
        PersistentCraftState state,
        PersistentCraftClientPrototypeCache prototypeCache,
        Action<string> onUnlock)
    {
        if (!ReferenceEquals(_prototypeCache, prototypeCache))
        {
            _prototypeCache = prototypeCache;
            _recipeIndex = PersistentCraftRecipeIndex.Create(prototypeCache);
            _branchRegistry = prototypeCache.BranchRegistry;
            _branchCoordinator.SetBranchRegistry(_branchRegistry);
            InitializeBranchHosts();
        }

        _state = state;
        _branchCoordinator.RebuildBranchStateIndex(state);
        _nodes = prototypeCache.AllNodes;
        _recipes = prototypeCache.AllRecipes;
        _onUnlock = onUnlock;

        if (state.Loaded && _viewModel.SelectPreferredBranchOnNextUpdate)
        {
            _branchCoordinator.SelectPreferredBranchTab(Branches);
            _viewModel.SelectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _viewModel.SelectPreferredBranchOnNextUpdate = true;
    }

    private void Render()
    {
        if (_state == null)
            return;

        RenderBranch(_branchCoordinator.GetCurrentBranch(Branches));
    }

    private void RenderBranch(string branch)
    {
        var subNodeHost = _branchCoordinator.GetBranchHost(branch);
        subNodeHost.RemoveAllChildren();

        if (_state == null)
            return;

        var branchSubNodes = GetNodesForBranch(branch);

        if (branchSubNodes.Count == 0)
        {
            CloseNodeDetailsWindow();
            return;
        }

        var branchState = _branchCoordinator.GetBranchState(branch);
        var selectedNode = _selectionCoordinator.ResolveSelectedNode(branch, branchSubNodes);

        subNodeHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-tree-label")));
        subNodeHost.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints}",
            FontColorOverride = GetBranchAccent(branch),
        });
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        if (branchSubNodes.Count == 0)
        {
            subNodeHost.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedTextColor,
            });
        }
        else
        {
            subNodeHost.AddChild(CreateSubNodeTree(branch, branchSubNodes, selectedNode?.ID));
        }

        if (selectedNode == null)
        {
            CloseNodeDetailsWindow();
            return;
        }

        if (_detailsCoordinator.IsOpen)
        {
            ShowNodeDetailsWindow(branchState, selectedNode);
        }
    }

    private static Label CreateSectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = HeaderTextColor,
        };
    }

    private void SelectNode(string branch, string nodeId)
    {
        var selectionDecision = _selectionCoordinator.OnNodePressed(branch, nodeId, _detailsCoordinator.IsOpen);
        if (selectionDecision.ShouldCloseDetails)
        {
            CloseNodeDetailsWindow();
            return;
        }

        if (_state == null)
            return;

        if (selectionDecision.SelectedNodeId is not { } selectedNodeId)
            return;

        if (!TryGetNodePrototype(selectedNodeId, out var node) ||
            !string.Equals(node.Branch, branch, StringComparison.Ordinal))
        {
            return;
        }

        var branchState = _branchCoordinator.GetBranchState(branch);
        ShowNodeDetailsWindow(branchState, node);
    }
}
