using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client._Stalker.PersistentCrafting;
using Content.Client._Stalker.PersistentCrafting.UI.Indexes;
using Content.Client._Stalker.PersistentCrafting.UI.Controls;
using Content.Client._Stalker.PersistentCrafting.UI.ViewModels;
using Content.Client.Message;
using Content.Shared._Stalker.PersistentCrafting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Stalker.PersistentCrafting.UI;

[GenerateTypedNameReferences]
public sealed partial class PersistentCraftingWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!;
    [Dependency] private readonly IClyde _clyde = default!;

    private static readonly Color WeaponAccent = PersistentCraftUiTheme.WeaponAccent;
    private static readonly Color ArmorAccent = PersistentCraftUiTheme.ArmorAccent;
    private static readonly Color AnomalyAccent = PersistentCraftUiTheme.AnomalyAccent;
    private static readonly Color PanelBackground = PersistentCraftUiTheme.SurfaceWindow;
    private static readonly Color CardBackground = PersistentCraftUiTheme.SurfacePanel;
    private static readonly Color CardUnlockedBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardLockedBackground = PersistentCraftUiTheme.SurfacePanelSoft;
    private static readonly Color CardAvailableBackground = PersistentCraftUiTheme.SurfacePanelAlt;
    private static readonly Color CardBorder = PersistentCraftUiTheme.Border;
    private static readonly Color AvailableBorder = PersistentCraftUiTheme.BorderStrong;
    private static readonly Color UnlockedBorder = PersistentCraftUiTheme.Success;
    private static readonly Color SelectedBorder = PersistentCraftUiTheme.Selection;
    private static readonly Color HeaderTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color MutedTextColor = PersistentCraftUiTheme.TextSecondary;
    private static readonly Color DescriptionTextColor = PersistentCraftUiTheme.TextPrimary;
    private static readonly Color IconBackground = PersistentCraftUiTheme.SurfaceInset;
    private const float TierTreeNodeWidth = 176f;
    private const float TierTreeNodeHeight = 178f;
    private const float TierTreeHorizontalGap = 56f;
    private const float TierTreeVerticalGap = 36f;
    private const float TierTreePadding = 24f;
    private const float TierTreeLineThickness = 3f;
    private const float NodeDetailsWindowWidth = 860f;
    private const float NodeDetailsWindowHeight = 720f;
    private const float NodeDetailsWindowMinWidth = 700f;
    private const float NodeDetailsWindowMinHeight = 560f;
    private const float NodeDetailsWindowMargin = 16f;

    private readonly Dictionary<string, BoxContainer> _branchHosts = new();
    private readonly Dictionary<string, PersistentCraftBranchState> _branchStateById = new();
    private readonly PersistentCraftSkillTreeViewModel _viewModel = new();

    private PersistentCraftRecipeIndex? _recipeIndex;
    private PersistentCraftState? _state;
    private PersistentCraftBranchRegistry _branchRegistry;
    private PersistentCraftClientPrototypeCache? _prototypeCache;
    private IReadOnlyList<PersistentCraftNodePrototype> _nodes = Array.Empty<PersistentCraftNodePrototype>();
    private IReadOnlyList<PersistentCraftRecipePrototype> _recipes = Array.Empty<PersistentCraftRecipePrototype>();
    private Action<string>? _onUnlock;
    private DefaultWindow? _nodeDetailsWindow;

    public PersistentCraftingWindow()
    {
        IoCManager.InjectDependencies(this);
        _branchRegistry = PersistentCraftBranchRegistry.Create(_prototype);

        RobustXamlLoader.Load(this);

        InitializeBranchHosts();
        PersistentCraftUiTheme.ApplyTabTheme(Branches, "persistent-craft-skill-tabs", PersistentCraftUiTheme.Selection, _uiManager);

        Branches.OnTabChanged += _ =>
        {
            CloseNodeDetailsWindow();
            RenderBranch(GetCurrentBranch());
        };
    }

    private void InitializeBranchHosts()
    {
        Branches.RemoveAllChildren();
        _branchHosts.Clear();

        for (var index = 0; index < _branchRegistry.OrderedBranches.Count; index++)
        {
            var definition = _branchRegistry.OrderedBranches[index];
            var host = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(12, 12, 12, 12),
            };

            var scroll = new ScrollContainer
            {
                MinSize = new Vector2(980, 0),
                HorizontalExpand = true,
                HScrollEnabled = true,
                VerticalExpand = true,
            };
            scroll.AddChild(host);
            Branches.AddChild(scroll);

            _branchHosts[definition.ID] = host;
            Branches.SetTabTitle(index, ResolveBranchTitle(definition));
        }
    }

    public override void Close()
    {
        CloseNodeDetailsWindow();
        base.Close();
    }

    public void UpdateState(
        PersistentCraftState state,
        PersistentCraftClientPrototypeCache prototypeCache,
        Action<string> onUnlock)
    {
        if (!ReferenceEquals(_prototypeCache, prototypeCache))
        {
            _prototypeCache = prototypeCache;
            _recipeIndex = PersistentCraftRecipeIndex.Create(prototypeCache);
            _branchRegistry = prototypeCache.BranchRegistry;
            InitializeBranchHosts();
        }

        _state = state;
        RebuildBranchStateIndex(state);
        _nodes = prototypeCache.AllNodes;
        _recipes = prototypeCache.AllRecipes;
        _onUnlock = onUnlock;

        if (state.Loaded && _viewModel.SelectPreferredBranchOnNextUpdate)
        {
            SelectPreferredBranchTab();
            _viewModel.SelectPreferredBranchOnNextUpdate = false;
        }

        Render();
    }

    public void ResetInitialTabSelection()
    {
        _viewModel.SelectPreferredBranchOnNextUpdate = true;
    }

    private void RebuildBranchStateIndex(PersistentCraftState state)
    {
        _branchStateById.Clear();
        for (var i = 0; i < state.BranchStates.Count; i++)
        {
            var branchState = state.BranchStates[i];
            _branchStateById[branchState.Branch] = branchState;
        }
    }

    private void Render()
    {
        if (_state == null)
            return;

        RenderBranch(GetCurrentBranch());
    }

    private void RenderBranch(string branch)
    {
        var subNodeHost = GetBranchHost(branch);
        subNodeHost.RemoveAllChildren();

        if (_state == null)
            return;

        var branchSubNodes = GetNodesForBranch(branch);

        if (branchSubNodes.Count == 0)
        {
            CloseNodeDetailsWindow();
            return;
        }

        var branchState = GetBranchState(_state, branch);
        var selectedNode = ResolveSelectedNode(branch, branchSubNodes);

        subNodeHost.AddChild(CreateSectionHeader(Loc.GetString("persistent-craft-tree-label")));
        subNodeHost.AddChild(new Label
        {
            Text = $"{Loc.GetString("persistent-craft-branch-points-label")}: {branchState.AvailablePoints}",
            FontColorOverride = GetBranchAccent(branch),
        });
        subNodeHost.AddChild(new Control { MinSize = new Vector2(1, 8) });
        if (branchSubNodes.Count == 0)
        {
            subNodeHost.AddChild(new Label
            {
                Text = Loc.GetString("persistent-craft-none"),
                FontColorOverride = MutedTextColor,
            });
        }
        else
        {
            subNodeHost.AddChild(CreateSubNodeTree(branch, branchSubNodes, selectedNode?.ID));
        }

        if (selectedNode == null)
        {
            CloseNodeDetailsWindow();
            return;
        }

        if (_nodeDetailsWindow != null &&
            !_nodeDetailsWindow.Disposed &&
            _nodeDetailsWindow.IsOpen)
        {
            ShowNodeDetailsWindow(branchState, selectedNode);
        }
    }

    private static Label CreateSectionHeader(string text)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = HeaderTextColor,
        };
    }

    private PersistentCraftNodePrototype? ResolveSelectedNode(
        string branch,
        IReadOnlyList<PersistentCraftNodePrototype> subNodes)
    {
        if (_viewModel.SelectedNodeByBranch.TryGetValue(branch, out var selectedId))
        {
            for (var i = 0; i < subNodes.Count; i++)
            {
                var node = subNodes[i];
                if (node.ID == selectedId)
                    return node;
            }

            _viewModel.SelectedNodeByBranch.Remove(branch);
        }

        return null;
    }

    private void SelectNode(string branch, string nodeId)
    {
        if (_viewModel.SelectedNodeByBranch.TryGetValue(branch, out var selectedId) &&
            selectedId == nodeId &&
            _nodeDetailsWindow != null &&
            !_nodeDetailsWindow.Disposed &&
            _nodeDetailsWindow.IsOpen)
        {
            _viewModel.SelectedNodeByBranch.Remove(branch);
            CloseNodeDetailsWindow();
            return;
        }

        _viewModel.SelectedNodeByBranch[branch] = nodeId;

        if (_state == null)
            return;

        if (!TryGetNodePrototype(nodeId, out var node) ||
            !string.Equals(node.Branch, branch, StringComparison.Ordinal))
        {
            return;
        }

        var branchState = GetBranchState(_state, branch);
        ShowNodeDetailsWindow(branchState, node);
    }

    private IReadOnlyList<PersistentCraftRecipePrototype> FindRecipesForNode(PersistentCraftNodePrototype node)
    {
        if (_recipeIndex != null)
        {
            return _recipeIndex.GetByRequiredNode(node.ID);
        }

        if (_prototypeCache != null &&
            _prototypeCache.RecipesByNode.TryGetValue(node.ID, out var cacheRecipes))
        {
            return cacheRecipes;
        }

        var recipes = new List<PersistentCraftRecipePrototype>();
        for (var i = 0; i < _recipes.Count; i++)
        {
            var recipe = _recipes[i];
            if (recipe.RequiredNode == node.ID)
                recipes.Add(recipe);
        }

        return recipes;
    }

    private bool TryGetNodeTexture(PersistentCraftNodePrototype node, out Texture? texture)
    {
        texture = null;

        var displayProto = node.DisplayProto;
        if (string.IsNullOrWhiteSpace(displayProto))
        {
            var recipes = FindRecipesForNode(node);
            if (recipes.Count > 0)
                displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipes[0]);
        }

        if (string.IsNullOrWhiteSpace(displayProto))
            return false;

        try
        {
            var spriteSystem = _entityManager.EntitySysManager.GetEntitySystem<SpriteSystem>();
            texture = spriteSystem.GetPrototypeIcon(displayProto).Default;
            return texture != null;
        }
        catch
        {
            texture = null;
            return false;
        }
    }

    private string ResolveRecipeName(PersistentCraftRecipePrototype recipe)
    {
        var displayProto = PersistentCraftingHelper.GetDisplayPrototypeId(recipe);
        if (!string.IsNullOrWhiteSpace(displayProto) &&
            _prototype.TryIndex<EntityPrototype>(displayProto, out var prototype))
        {
            return prototype.Name;
        }

        return Loc.GetString(recipe.Name);
    }

    private string ResolveNodeName(PersistentCraftNodePrototype node)
    {
        if (!string.IsNullOrWhiteSpace(node.Name))
        {
            if (Loc.TryGetString(node.Name, out var localizedNodeName) &&
                !string.IsNullOrWhiteSpace(localizedNodeName))
            {
                return localizedNodeName;
            }

            if (!string.IsNullOrWhiteSpace(node.Name))
                return node.Name;
        }

        if (!string.IsNullOrWhiteSpace(node.DisplayProto) &&
            _prototype.TryIndex<EntityPrototype>(node.DisplayProto, out var prototype))
        {
            if (!string.IsNullOrWhiteSpace(prototype.Name))
            {
                return prototype.Name;
            }

            if (Loc.TryGetString($"ent-{prototype.ID}", out var localizedPrototypeName) &&
                !string.IsNullOrWhiteSpace(localizedPrototypeName))
            {
                return localizedPrototypeName;
            }

            return prototype.ID;
        }

        if (!string.IsNullOrWhiteSpace(node.DisplayProto))
            return node.DisplayProto;

        return node.ID;
    }

    private string ResolveNodeCardCaption(PersistentCraftNodePrototype node)
    {
        var resolved = ResolveNodeName(node).Trim();
        if (!string.IsNullOrWhiteSpace(resolved))
            return resolved;

        if (!string.IsNullOrWhiteSpace(node.DisplayProto))
            return node.DisplayProto;

        return node.ID;
    }

    private void SelectPreferredBranchTab()
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        var preferredBranch = string.Empty;
        var bestPoints = 0;

        for (var i = 0; i < _branchRegistry.OrderedBranchIds.Count; i++)
        {
            var branch = _branchRegistry.OrderedBranchIds[i];
            var points = GetBranchState(state, branch).AvailablePoints;
            if (points <= bestPoints)
                continue;

            bestPoints = points;
            preferredBranch = branch;
        }

        if (!string.IsNullOrWhiteSpace(preferredBranch) &&
            _branchRegistry.TryGetBranchIndex(preferredBranch, out var branchIndex))
        {
            Branches.CurrentTab = branchIndex;
        }
    }

    private string GetCurrentBranch()
    {
        return _branchRegistry.TryGetBranchByIndex(Branches.CurrentTab, out var branch)
            ? branch
            : (_branchRegistry.FirstBranchId is { Length: > 0 } first ? first : GetAnyBranchId());
    }

    private string GetAnyBranchId()
    {
        foreach (var key in _branchHosts.Keys)
        {
            return key;
        }

        return string.Empty;
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId)
    {
        if (_state == null)
            return false;

        return HasNodeUnlockedOrAutoAvailable(nodeId, new HashSet<string>());
    }

    private bool HasNodeUnlockedOrAutoAvailable(string nodeId, HashSet<string> path)
    {
        var state = _state ?? throw new InvalidOperationException("Persistent craft state is not initialized.");

        if (!TryGetNodePrototype(nodeId, out var node))
            return false;

        if (state.UnlockedNodes.Contains(nodeId))
            return true;

        if (node.Cost > 0)
            return false;

        if (!path.Add(nodeId))
            return false;

        try
        {
            return node.Prerequisites.All(prerequisite => HasNodeUnlockedOrAutoAvailable(prerequisite, path));
        }
        finally
        {
            path.Remove(nodeId);
        }
    }

    private BoxContainer GetBranchHost(string branch)
    {
        if (_branchHosts.TryGetValue(branch, out var host))
            return host;

        if (_branchHosts.Count > 0)
            return _branchHosts.Values.First();

        throw new InvalidOperationException("Persistent craft skill branches are not initialized.");
    }

    private PersistentCraftBranchState GetBranchState(PersistentCraftState state, string branch)
    {
        if (_branchStateById.TryGetValue(branch, out var branchState))
            return branchState;

        return new PersistentCraftBranchState(
            branch,
            0,
            0);
    }

    private Color GetBranchAccent(string branch)
    {
        return _branchRegistry.TryGetBranchDefinition(branch, out var definition)
            ? definition.AccentColor
            : Color.White;
    }

    private string ResolveBranchTitle(string branchId)
    {
        return _branchRegistry.TryGetBranchDefinition(branchId, out var definition)
            ? ResolveBranchTitle(definition)
            : branchId;
    }

    private IReadOnlyList<PersistentCraftNodePrototype> GetNodesForBranch(string branch)
    {
        if (_prototypeCache != null &&
            _prototypeCache.NodesByBranch.TryGetValue(branch, out var nodes))
        {
            return nodes;
        }

        var filtered = new List<PersistentCraftNodePrototype>();
        for (var i = 0; i < _nodes.Count; i++)
        {
            var node = _nodes[i];
            if (node.Branch == branch)
                filtered.Add(node);
        }

        return filtered;
    }

    private bool TryGetNodePrototype(string nodeId, out PersistentCraftNodePrototype node)
    {
        if (_prototypeCache != null &&
            _prototypeCache.TryGetNode(nodeId, out node))
        {
            return true;
        }

        if (_prototype.TryIndex<PersistentCraftNodePrototype>(nodeId, out var resolvedNode) &&
            resolvedNode != null)
        {
            node = resolvedNode;
            return true;
        }

        node = default!;
        return false;
    }

    private static string ResolveBranchTitle(PersistentCraftBranchPrototype definition)
    {
        try
        {
            return Loc.GetString(definition.Name);
        }
        catch
        {
            return definition.Name;
        }
    }
}
