using System.IO;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.Private.Scr.UI;

[GenerateTypedNameReferences]
public sealed partial class ScrUi : DefaultWindow
{
    private readonly ISawmill _logger;
    public ScrUi()
    {
        _logger = Logger.GetSawmill("scr.ui");
        RobustXamlLoader.Load(this);
    }

    public void SetIsValid(bool isValid)
    {
        // There are no Secrets' .ftls on client, I had to do it.
        IsValid.Text = isValid
            ? "EXIF: Корректный"
            : "EXIF: Некорректный, возможно изменён сторонними средствами";

        IsValid.FontColorOverride = isValid ? Color.Green : Color.Red;
    }

    public void SetImage(byte[] imageData)
    {
        try
        {
            var stream = new MemoryStream(imageData);
            ImageDisplay.Texture = Texture.LoadFromPNGStream(stream);
        }
        catch (Exception ex)
        {
            _logger.Error($"Failed to load image: {ex}");
        }
    }
}
