using Content.Client._Stalker_EN.FactionRelations;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Stalker_EN.PdaMessenger;

/// <summary>
/// A contact row in the main page's contact list, showing name, messenger ID, and unread badge.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class STMessengerContactRow : BoxContainer
{
    /// <summary>Raised when the user clicks the contact row to open the DM conversation.</summary>
    public event Action? OnSelected;

    /// <summary>Raised when the user clicks the remove button to delete this contact.</summary>
    public event Action? OnRemove;

    public STMessengerContactRow(string contactName, int unreadCount, string? messengerId, string? factionName, string? rankIcon = null)
    {
        RobustXamlLoader.Load(this);

        ContactNameLabel.Text = contactName;

        var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

        if (factionName is not null
            && STFactionPatchIcons.PatchStates.TryGetValue(factionName, out var patch))
        {
            var specifier = new SpriteSpecifier.Rsi(patch.Rsi, patch.State);
            FactionIcon.Texture = spriteSystem.Frame0(specifier);
            FactionIcon.Visible = true;
        }

        if (rankIcon is not null)
        {
            var protoManager = IoCManager.Resolve<IPrototypeManager>();
            if (protoManager.TryIndex<JobIconPrototype>(rankIcon, out var rankProto))
            {
                RankIcon.Texture = spriteSystem.Frame0(rankProto.Icon);
                RankIcon.Visible = true;
            }
        }

        PdaIdLabel.Text = messengerId ?? string.Empty;
        PdaIdLabel.Visible = messengerId is not null;

        UnreadLabel.Text = unreadCount > 0
            ? Loc.GetString("st-messenger-unread-count", ("count", unreadCount))
            : string.Empty;
        UnreadLabel.Visible = unreadCount > 0;

        SelectButton.OnPressed += _ => OnSelected?.Invoke();
        RemoveButton.OnPressed += _ => OnRemove?.Invoke();
    }
}
